### ISSUE TITLE
Enable password encryption

### ISSUE THREAD

**Issue by wirion** [Share2U-Project/Share2U#7]

**Comment by matthieu88160** [comment]
You can refer to https://github.com/matthieu88160/wf/blob/master/SILEX-exo1/src/UserController/UserController.php form signup encryption.
By default, Silex uses the BCrypt algorithm to encode passwords. Additionally, the password is encoded multiple times. So, just remove the encoder part of the firewall configuration.

**Comment by wirion** [comment]
Done, thanks Matthieu for the comment
